### ISSUE TITLE
Updating some examples to have a better structure

### ISSUE THREAD

**Issue by Th3T3chn0G1t** [gbdk-2020/gbdk-2020#169]
Heyo,

Opening this mainly as a tag target for PRs

Just some issues with examples which need to be addressed:
- The structure of the examples could be reworked - i.e. separate `src` and `obj` folders for building
- Some of the content is a obscure or unclear
- Some of the content contains outdated paradigms (https://github.com/gbdk-2020/gbdk-2020/issues/162)
- The structure of the `examples` folder could be reworked into more specific categories
- More broad examples implementing games or demos

I'll make a pr about some of the structural stuff in a bit!

**Comment by bbbbbr** [comment]
@untoxa has suggested a couple things:
* For `src` only those example worth reorganizing, that contain several source files
* `obj` folder is not needed for one-line (lcc -o out.gb in1.c in2.c ...) compile examples since that does not leave any objects behind
* It is worth making new examples instead of tuning the old ones, we are lacking some basic examples
* Maybe reorganize the structure like: examples/games, examples/beginner, examples/hardware

Some of my thoughts:
* We can give people a better base to build from. Many people will just copy, use and build on what they find (and perhaps ignore the template projects), so having samples be more uniform a little better organized could save some trouble in long run. 
* Having `src` and `obj` or equivalents can help make the projects generally tidier
* Would be nice for the makefiles to generally harmonized and not have too many different variants
* Having comments in the makefile to explain what is being done and why is useful. I've been trying to do that in some of the more recent examples.
* GBDK Playground has some useful examples we may want to consider or be inspired by (may need updating to GBDK-2020 from gbdk 2.x): https://github.com/mrombout
* The scope for improving the example projects can be small or big :)

**Comment by Th3T3chn0G1t** [comment]
Regarding the hardcoding of the compiler path in the example makefiles - might it be an idea to set an env variable at installation/tell the user to set an env variable pointing to the binaries. That way the examples can be used without modification whether gbdk binaries are installed to the `PATH` or otherwise
