### ISSUE TITLE
png2asset: -source_tileset doesn't play nice with -use_structs

### ISSUE THREAD

**Issue by joshbalfour** [gbdk-2020/gbdk-2020#610]
First off, thank you so, so much for this project - it's making gameboy dev accessible to lowly web devs like me (for better or worse :D) 

(I've tried both 4.2.0 and [the latest build from master](https://github.com/gbdk-2020/gbdk-2020/actions/runs/7501751116))

I've noticed that if you go
```
png2asset ../res/zfile.png -map -source_tileset ../res/tfile.png
```
everything seems to work fine.

But if you add `-use_structs` onto that you get:

```
compiling resource ../DebugColor/res/tfile.png.c
Got 9 tiles from the source tileset.
Got 1 palettes from the source tileset.
compiling resource ../DebugColor/res/zmfile.png.c
../DebugColor/res/zmfile.png.c:41: error 20: Undefined identifier 'zmfile_tiles_info'
../DebugColor/res/zmfile.png.c:41: error 47: indirections to different types assignment
from type 'int near* fixed'
  to type 'struct TilesInfo generic* fixed'
../DebugColor/res/zmfile.png.c:41: warning 18: Initializer different levels of indirections
from type 'int near* fixed'
  to type 'struct TilesInfo generic* fixed'
make: *** [../DebugColor/res/zmfile.png.o] Error 1
```

I'm using ZGB so I need it to output structs for it to play nice with ZGB.

The way I got to this (if helpful) is I'm trying to use PNGs for my maps in ZGB with a tileset, so that I can use the tile index predictably.

tfile.png
![tfile](https://github.com/gbdk-2020/gbdk-2020/assets/1060378/a0552328-c76a-427a-bb99-364ead66a920)

zmfile.png
![zmfile](https://github.com/gbdk-2020/gbdk-2020/assets/1060378/44f3129c-9b2b-4bea-8a17-1c42bc05c505)

Thanks again!

**Comment by bbbbbr** [comment]
Looks like it may be (mostly) working as designed right now, but in a way which doesn't meet the additional expectations of ZGB.

When `-source_tileset` is specified it only writes tile data/palettes/etc out if new entries are found which are not present in the source tileset.

However ZGB seems to expect:
- A `___tiles_info {}` struct to be generated regardless of whether any new tiles are found
- And probably the same for `___tiles[]`, `____tile_pals[]` and `___palettes[]` regardless of whether they're empty or not

Right on the version in the `develop` branch (and CI) if you create a single novel tile in the map you can see that it begins to export some of the missing arrays.

It is probably not hard to force output of those entries for even if they are empty when `-use_structs` is present for ZGB.

However that still wouldn't include the source tileset data, so that would still have to get loaded. Did you envision having that data be included in the output, or manually loading it on your own from a separate file?

Going to @Zal0 into this since he may have some opinions about the right way to support this.

**Comment by untoxa** [comment]
taking into account the CrossZGB development: https://github.com/gbdk-2020/CrossZGB , behavior for the `-source_tileset` in conjunction with `-use_structs` was changed. MapInfo structs now reference the external source tileset. that behavior is not final yet, because C files miss the tile data which is extracted from the image, but not exist in the source tileset. that current state is ok for the CrossZGB current needs, where you need to produce maps from the PNGs. but MapInfo struct will be extended to include the pointer to the unique tiles from the image.
