### ISSUE TITLE
VSCode problem from 'BANKREF' when using png2asset

### ISSUE THREAD

**Issue by weleusernamegod** [gbdk-2020/gbdk-2020#640]
I have added png2asset to my build task in VSCode. It works as I'm able to generate my assets every time I build the project. Annoyingly I always get an error / red squiggly line because of the 'BANKREF()' call in the .c file. Is there an option to not export this function when generating the .c file?

This is the command I'm using:
`/usr/local/opt/gbdk/bin/png2asset assets/rover.png -spr8x8 -c data/rover.c -tiles_only -no_palettes`

**Comment by bbbbbr** [comment]
The squiggle is just a warning hint likely because vscode can't find the macro in the header files (due to lack of platform definition).

Trying making the vscode config changes here, particularly `"defines": ["__PORT_sm83", "__TARGET_gb"],` so that the target platform is set when parsing gbdk header files. This is part of the docs for the next release.

Scroll down to the `@anchor code_editors_hinting` note on this page:
https://github.com/gbdk-2020/gbdk-2020/blob/develop/docs/pages/02_links_and_tools.md#emulators

**Comment by weleusernamegod** [comment]
Thank you for your reply! I tried to edit my config file and add this line of code, but to no avail. Now my project has become so big that I have to use BANKREF in my main code files aswell, so now I have this vscode error everytime I compile.

This is how my `c_cpp_properties.json` looks like. Any idea on how to fix this issue?
```
{
    "configurations": [
        {
            "name": "gameboy",
            "includePath": [
                "/usr/local/opt/gbdk/include"
            ],
            "defines": ["__PORT_sm83", "__TARGET_gb"],
            "macFrameworkPath": [
                "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks"
            ],
            "compilerPath": "/usr/bin/clang",
            "cStandard": "c17",
            "cppStandard": "c++17",
            "intelliSenseMode": "macos-clang-arm64"
        }
    ],
    "version": 4
}
```

**Comment by bbbbbr** [comment]
Unless you are getting an actual SDCC compiler build error (if so please include it) we'll consider this as a VS Code configuration issue and outside the scope of GBDK.
