### ISSUE TITLE
Add support for ARM Linux (Raspberry Pi)

### ISSUE THREAD

**Issue by ReptiIe** [gbdk-2020/gbdk-2020#667]
Hello,
I search the issues, and I see I am not the only one asking for this feature,
would it be possible to add support for ARM Linux? 
We would love to develop GBStudio app for Raspberry Pi users,
sadly ARM LINUX support for GBDK is required for this.

Good day! 😄

**Comment by bbbbbr** [comment]
Currently we don't have ARM Linux builds for SDCC since that platform is not natively supported by Github Runners. (if you have experience with them and would like to PR support, we're open to reviewing that).

You can try following the SDCC build and patch instructions in the issue linked below from our SDCC build repo. If you manage to do that then building GBDK itself from source should be fairly easy.
https://github.com/gbdk-2020/gbdk-2020-sdcc/issues/3

Note: Looks like there is some progress toward Linux ARM runners, but it's not there yet. If that happens we can likely add a Linux ARM build without too much trouble.
https://github.com/orgs/community/discussions/19197

**Comment by asiekierka** [comment]
https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/

**Comment by bbbbbr** [comment]
Awesome, thanks!

And good timing, as we will soon begin working on updating the toolchain to the newer sdcc.

**Comment by bbbbbr** [comment]
Added it to the gbdk build process, there are some pre-release binaries up at:
https://github.com/gbdk-2020/gbdk-2020/releases/tag/gbdk-next
